# Generated by Django 4.0.1 on 2022-04-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('url', models.CharField(max_length=1000)),
                ('picture', models.ImageField(upload_to='site_media')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('parent_picture', models.IntegerField()),
            ],
        ),
    ]
