# Generated by Django 4.0.1 on 2022-04-07 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_photo_parent_picture_alter_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.FileField(upload_to='site_media'),
        ),
    ]
