# Generated by Django 4.0.1 on 2022-04-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_photo_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.FileField(null=True, upload_to='site_media'),
        ),
    ]
