# Generated by Django 4.0.1 on 2022-04-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_photo_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='picture',
            field=models.FileField(upload_to='site_media'),
        ),
    ]
